# Generated by Django 5.2.5 on 2025-08-21 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenVPNServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя сервера')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('host', models.GenericIPAddressField(protocol='IPv4', verbose_name='IP адрес')),
                ('ssh_port', models.PositiveIntegerField(default=22, verbose_name='SSH порт')),
                ('ssh_username', models.CharField(max_length=50, verbose_name='SSH пользователь')),
                ('ssh_password', models.CharField(blank=True, max_length=255, verbose_name='SSH пароль')),
                ('ssh_key_path', models.CharField(blank=True, max_length=500, verbose_name='Путь к SSH ключу')),
                ('openvpn_port', models.PositiveIntegerField(default=1194, verbose_name='OpenVPN порт')),
                ('openvpn_protocol', models.CharField(choices=[('udp', 'UDP'), ('tcp', 'TCP')], default='udp', max_length=3, verbose_name='Протокол')),
                ('server_subnet', models.GenericIPAddressField(default='10.8.0.0', protocol='IPv4', verbose_name='Подсеть сервера')),
                ('server_netmask', models.GenericIPAddressField(default='255.255.255.0', protocol='IPv4', verbose_name='Маска подсети')),
                ('dns_servers', models.JSONField(default=list, help_text='Список DNS серверов в формате JSON', verbose_name='DNS серверы')),
                ('status', models.CharField(choices=[('pending', 'Pending Installation'), ('installing', 'Installing'), ('installed', 'Installed'), ('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error')], default='pending', max_length=20, verbose_name='Статус')),
                ('last_check', models.DateTimeField(blank=True, null=True, verbose_name='Последняя проверка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'OpenVPN Сервер',
                'verbose_name_plural': 'OpenVPN Серверы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email клиента')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('client_cert', models.TextField(verbose_name='Клиентский сертификат')),
                ('client_key', models.TextField(verbose_name='Клиентский ключ')),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Отозван')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='ovpn_app.openvpnserver', verbose_name='Сервер')),
            ],
            options={
                'verbose_name': 'Клиентский Сертификат',
                'verbose_name_plural': 'Клиентские Сертификаты',
                'ordering': ['-created_at'],
                'unique_together': {('server', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CertificateAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='RU', max_length=2, verbose_name='Страна')),
                ('state', models.CharField(default='Moscow', max_length=100, verbose_name='Область')),
                ('city', models.CharField(default='Moscow', max_length=100, verbose_name='Город')),
                ('organization', models.CharField(max_length=100, verbose_name='Организация')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('ca_cert', models.TextField(verbose_name='CA сертификат')),
                ('ca_key', models.TextField(verbose_name='CA ключ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ca', to='ovpn_app.openvpnserver', verbose_name='Сервер')),
            ],
            options={
                'verbose_name': 'Центр Сертификации',
                'verbose_name_plural': 'Центры Сертификации',
            },
        ),
        migrations.CreateModel(
            name='ServerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('install', 'Install OpenVPN'), ('configure', 'Configure Server'), ('create_client', 'Create Client'), ('revoke_client', 'Revoke Client'), ('check_status', 'Check Status')], max_length=20, verbose_name='Тип задачи')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Статус')),
                ('task_id', models.CharField(max_length=255, unique=True, verbose_name='ID задачи')),
                ('parameters', models.JSONField(default=dict, verbose_name='Параметры')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='Результат')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='Прогресс (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начато')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ovpn_app.openvpnserver', verbose_name='Сервер')),
            ],
            options={
                'verbose_name': 'Задача Сервера',
                'verbose_name_plural': 'Задачи Серверов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VPNConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='IP клиента')),
                ('virtual_ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='Виртуальный IP')),
                ('bytes_received', models.BigIntegerField(default=0, verbose_name='Получено байт')),
                ('bytes_sent', models.BigIntegerField(default=0, verbose_name='Отправлено байт')),
                ('connected_at', models.DateTimeField(auto_now_add=True, verbose_name='Подключен')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='ovpn_app.clientcertificate', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'VPN Подключение',
                'verbose_name_plural': 'VPN Подключения',
                'ordering': ['-connected_at'],
            },
        ),
    ]
