# Generated by Django 5.2.5 on 2025-08-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovpn_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openvpnserver',
            name='ssh_private_key',
            field=models.TextField(blank=True, verbose_name='SSH приватный ключ'),
        ),
    ]
