# Generated by Django 5.2.5 on 2025-11-11 23:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovpn_app', '0002_openvpnserver_ssh_private_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnconnection',
            name='connected_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Подключен'),
        ),
    ]
