# Generated by Django 5.2.5 on 2025-11-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ovpn_app", "0003_alter_vpnconnection_connected_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="openvpnserver",
            name="stunnel_enabled",
            field=models.BooleanField(
                default=False, help_text="Stunnel сервис запущен", verbose_name="Stunnel активен"
            ),
        ),
        migrations.AddField(
            model_name="openvpnserver",
            name="stunnel_port",
            field=models.PositiveIntegerField(
                default=443,
                help_text="Внешний порт для подключения клиентов через Stunnel",
                verbose_name="Stunnel порт",
            ),
        ),
        migrations.AddField(
            model_name="openvpnserver",
            name="use_stunnel",
            field=models.BooleanField(
                default=False,
                help_text="Включить Stunnel для OpenVPN через TCP/TLS",
                verbose_name="Использовать Stunnel",
            ),
        ),
    ]
